### ISSUE TITLE
建议支持 \r\n 换行的文件

### ISSUE THREAD

**Issue by baight** [azone/WYZLRCParser#3]
在 parseLRC 方法里，
NSArray \* lines = [LRCString componentsSeparatedByString:@"\n"];
改为
NSArray \* lines = [LRCString componentsSeparatedByString:@"\r\n"];
if(lines.count == 0){
    lines = [LRCString componentsSeparatedByString:@"\n"];
}
这样就更好了

**Comment by baight** [comment]
是
NSArray \* lines = [LRCString componentsSeparatedByString:@"\r\n"];
if(lines.count <= 1){
lines = [LRCString componentsSeparatedByString:@"\n"];
}

**Comment by azone** [comment]
`\r\n` 本身就已经包含 `\r` ，而且 `\r` 是不可见字符，所以不会有影响的

**Comment by baight** [comment]
但是在计算str.length上，会多莫名一个哦

**Comment by azone** [comment]
@baight 今晚再优化一下吧，前后把不可见字符和空格去掉
